name: fenrir

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: https://git.szamszur.cloud/upstream-actions/paths-filter@f3ceefdc7ef57bc2d8560787d4b6c33e44044cec
        id: filter
        with:
          filters: |
            build:
              - "hosts/fenrir/**"
              - ".github/workflows/fenrir.yml"
              - "modules/**"
              - "pkgs/**"
              - "flake.nix"
              - "flake.lock"
  nix-build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.build == 'true' }}
    runs-on: nixos

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - name: Build fenrir
      run: nix build .#nixosConfigurations.fenrir.config.system.build.toplevel -L --accept-flake-config