[font]
size = 10.0

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[general]
live_config_reload = true