name: fenrir

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # This job checks if an identical workflow is being triggered by different
  # event and skips it. For instance there is no need to run the same pipeline
  # twice for pull_request and push for identical commit sha.
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@v4
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          skip_after_successful_duplicate: 'true'
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            build:
              - "hosts/fenrir/**"
              - ".github/workflows/fenrir.yml"
              - "modules/**"
              - "pkgs/**"
              - "flake.nix"
              - "flake.lock"
  nix-build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' && needs.pre_job.outputs.build == 'true' }}
    runs-on: nixos

    steps:
    - uses: actions/checkout@v4
    - name: Build fenrir
      env:
        RCU_PRODUCT_KEY: ${{ secrets.RCU_PRODUCT_KEY }}
      run: nix build .#nixosConfigurations.fenrir.config.system.build.toplevel --impure -L --accept-flake-config