name: Update flake
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@9a59e15a74545c99a626ba594edcd0d02189e670
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@3c4f567004c3b0f7bb85177df020f3825028d2b1
        with:
          pr-title: "Update flake.lock"
          pr-assignees: rszamszur
          commit-msg: "chore: updates flake.lock"
          token: ${{ secrets.API_GITHUB_TOKEN }}
          pr-labels: |
            dependencies
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
