name: Update flake
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1cce3390c2bfda521930d01229c073c7ff920824
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@1d87d45818068401a10cf16bdc5f00b24994a83f
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@fd9359ac79d0e912f1b4b947a48470b3e2799b56
        with:
          pr-title: "Update flake.lock"
          pr-assignees: rszamszur
          commit-msg: "chore: updates flake.lock"
          token: ${{ secrets.API_GITHUB_TOKEN }}
          pr-labels: |
            dependencies
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
